# Note: This package, `keras-core`, is not related to the Keras deep learning library;
# it is a separate package with its own functionality. 
# See also https://keras.io/keras_core/
{% set name = "keras-core" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/keras-core-{{ version }}.tar.gz
  sha256: a68580dc6910662026afdb5cda21e157f5163c6a77e86beae0e8d1de40234c07

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - absl-py
    - numpy
    - rich
    - namex
    - h5py
    - dm-tree
    - tensorflow

test:
  imports:
    - keras_core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/keras-team/keras-core
  summary: Multi-backend Keras.
  description: |
    A multi-backend implementation of the Keras API, with support for TensorFlow, JAX, and PyTorch.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://keras.io/keras_core/

extra:
  recipe-maintainers:
    - Anselmoo
